name: Take images for comparison

on:
  repository_dispatch:
    types: [my-event]

permissions: write-all

jobs:
  push_images:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: dev
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install selenium
          pip install --upgrade Pillow
          pip install Wand
          pip install webdriver-manager
      - name: test
        run: echo "${{toJSON(github.event.head_commit)}}"
      - name: take images
        run: |
          python src/main.py
          python src/mainFirefox.py
      - name: Commit report 
        run: |
          git config --global user.name "PmaFynn"
          git config --global user.email "fynn120801@gmail.com"
          git add .
          git commit -m "Automated report"
          git push
