# Define name
name: Node Continuous Integration
# Event that triggers workflow 
# honorable mentions:
# on: pull request
# on: repository_dispatch:
on:
  push:
    branches: [ master ]
# Optional provision of permissions
permissions: write-all
# Define job(s)
jobs:
  # Define name of job
  build_deploy_visualRegressionTest_dispatch:
    # Specify operating system (ubuntu, windows or mac)
    runs-on: ubuntu-latest
    # Steps to fulfill a job
    steps:
      - uses: actions/checkout@v3 # predefined action
      - uses: actions/setup-node@v3 # predefined action
        with: 
          node-version: 18
      - run: npm ci  # similiar to npm install
      # Optinal defining of a name for a specific step
      - name: Deploy # deployment of website
        run: |
          git config --global user.name "Fynn_Friedrichs"
          git config --global user.email "Fynn120801@gmail.com"
          git remote set-url origin https://${github_token}@github.com/${repository}
          npm run deploy
        env:
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2 # predefined action
        with:
          token: ${{ secrets.DISPATCH_WORKFLOW }}
          repository: PmaFynn/BA_v1
          event-type: my-event
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'





