name: Node Continuous Integration

on:
  push:
    branches: [ master ]

jobs:
  test_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 18
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: browser-actions/setup-chrome@latest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install selenium
          pip install --upgrade Pillow
          pip install Wand
      - run: npm ci
      - run: npm run build --if-present
      - run: pytest